### YamlMime:ManagedReference
items:
- uid: Google.Apis.Http.ConfigurableHttpClient
  commentId: T:Google.Apis.Http.ConfigurableHttpClient
  id: ConfigurableHttpClient
  parent: Google.Apis.Http
  children:
  - Google.Apis.Http.ConfigurableHttpClient.#ctor(Google.Apis.Http.ConfigurableMessageHandler)
  - Google.Apis.Http.ConfigurableHttpClient.MessageHandler
  langs:
  - csharp
  - vb
  name: ConfigurableHttpClient
  nameWithType: ConfigurableHttpClient
  fullName: Google.Apis.Http.ConfigurableHttpClient
  type: Class
  source:
    remote:
      path: Src/Support/Google.Apis.Core/Http/ConfigurableHttpClient.cs
      branch: master
      repo: https://github.com/google/google-api-dotnet-client
    id: ConfigurableHttpClient
    path: Src/Support/Google.Apis.Core/Http/ConfigurableHttpClient.cs
    startLine: 24
  assemblies:
  - Google.Apis.Core
  namespace: Google.Apis.Http
  summary: "\nConfigurable HTTP client inherits from <see cref=\"!:System.Net.Http.HttpClient\"></see> and contains a reference to \n<xref href=\"Google.Apis.Http.ConfigurableMessageHandler\" data-throw-if-not-resolved=\"false\"></xref>.\n"
  example: []
  syntax:
    content: 'public class ConfigurableHttpClient : HttpClient'
    content.vb: >-
      Public Class ConfigurableHttpClient
          Inherits HttpClient
  inheritance:
  - System.Object
  extensionMethods:
  - Google.Apis.Http.ConfigurableHttpClient.Google.Apis.Util.Utilities.ThrowIfNull``1(System.String)
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Google.Apis.Http.ConfigurableHttpClient.MessageHandler
  commentId: P:Google.Apis.Http.ConfigurableHttpClient.MessageHandler
  id: MessageHandler
  parent: Google.Apis.Http.ConfigurableHttpClient
  langs:
  - csharp
  - vb
  name: MessageHandler
  nameWithType: ConfigurableHttpClient.MessageHandler
  fullName: Google.Apis.Http.ConfigurableHttpClient.MessageHandler
  type: Property
  source:
    remote:
      path: Src/Support/Google.Apis.Core/Http/ConfigurableHttpClient.cs
      branch: master
      repo: https://github.com/google/google-api-dotnet-client
    id: MessageHandler
    path: Src/Support/Google.Apis.Core/Http/ConfigurableHttpClient.cs
    startLine: 27
  assemblies:
  - Google.Apis.Core
  namespace: Google.Apis.Http
  summary: Gets the configurable message handler.
  example: []
  syntax:
    content: public ConfigurableMessageHandler MessageHandler { get; }
    parameters: []
    return:
      type: Google.Apis.Http.ConfigurableMessageHandler
    content.vb: Public ReadOnly Property MessageHandler As ConfigurableMessageHandler
  overload: Google.Apis.Http.ConfigurableHttpClient.MessageHandler*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Google.Apis.Http.ConfigurableHttpClient.#ctor(Google.Apis.Http.ConfigurableMessageHandler)
  commentId: M:Google.Apis.Http.ConfigurableHttpClient.#ctor(Google.Apis.Http.ConfigurableMessageHandler)
  id: '#ctor(Google.Apis.Http.ConfigurableMessageHandler)'
  parent: Google.Apis.Http.ConfigurableHttpClient
  langs:
  - csharp
  - vb
  name: ConfigurableHttpClient(ConfigurableMessageHandler)
  nameWithType: ConfigurableHttpClient.ConfigurableHttpClient(ConfigurableMessageHandler)
  fullName: Google.Apis.Http.ConfigurableHttpClient.ConfigurableHttpClient(Google.Apis.Http.ConfigurableMessageHandler)
  type: Constructor
  source:
    remote:
      path: Src/Support/Google.Apis.Core/Http/ConfigurableHttpClient.cs
      branch: master
      repo: https://github.com/google/google-api-dotnet-client
    id: .ctor
    path: Src/Support/Google.Apis.Core/Http/ConfigurableHttpClient.cs
    startLine: 30
  assemblies:
  - Google.Apis.Core
  namespace: Google.Apis.Http
  summary: Constructs a new HTTP client.
  example: []
  syntax:
    content: public ConfigurableHttpClient(ConfigurableMessageHandler handler)
    parameters:
    - id: handler
      type: Google.Apis.Http.ConfigurableMessageHandler
    content.vb: Public Sub New(handler As ConfigurableMessageHandler)
  overload: Google.Apis.Http.ConfigurableHttpClient.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Google.Apis.Http.ConfigurableMessageHandler
  commentId: T:Google.Apis.Http.ConfigurableMessageHandler
  parent: Google.Apis.Http
  isExternal: false
  name: ConfigurableMessageHandler
  nameWithType: ConfigurableMessageHandler
  fullName: Google.Apis.Http.ConfigurableMessageHandler
- uid: Google.Apis.Http
  commentId: N:Google.Apis.Http
  isExternal: false
  name: Google.Apis.Http
  nameWithType: Google.Apis.Http
  fullName: Google.Apis.Http
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Google.Apis.Http.ConfigurableHttpClient.Google.Apis.Util.Utilities.ThrowIfNull``1(System.String)
  commentId: M:Google.Apis.Util.Utilities.ThrowIfNull``1(``0,System.String)
  parent: Google.Apis.Util.Utilities
  definition: Google.Apis.Util.Utilities.ThrowIfNull``1(``0,System.String)
  name: ThrowIfNull<ConfigurableHttpClient>(String)
  nameWithType: Utilities.ThrowIfNull<ConfigurableHttpClient>(String)
  fullName: Google.Apis.Util.Utilities.ThrowIfNull<Google.Apis.Http.ConfigurableHttpClient>(System.String)
  nameWithType.vb: Utilities.ThrowIfNull(Of ConfigurableHttpClient)(String)
  fullName.vb: Google.Apis.Util.Utilities.ThrowIfNull(Of Google.Apis.Http.ConfigurableHttpClient)(System.String)
  name.vb: ThrowIfNull(Of ConfigurableHttpClient)(String)
  spec.csharp:
  - uid: Google.Apis.Util.Utilities.ThrowIfNull``1(System.String)
    name: ThrowIfNull<ConfigurableHttpClient>
    nameWithType: Utilities.ThrowIfNull<ConfigurableHttpClient>
    fullName: Google.Apis.Util.Utilities.ThrowIfNull<Google.Apis.Http.ConfigurableHttpClient>
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Google.Apis.Util.Utilities.ThrowIfNull``1(System.String)
    name: ThrowIfNull(Of ConfigurableHttpClient)
    nameWithType: Utilities.ThrowIfNull(Of ConfigurableHttpClient)
    fullName: Google.Apis.Util.Utilities.ThrowIfNull(Of Google.Apis.Http.ConfigurableHttpClient)
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Google.Apis.Util.Utilities.ThrowIfNull``1(``0,System.String)
  commentId: M:Google.Apis.Util.Utilities.ThrowIfNull``1(``0,System.String)
  isExternal: true
  name: ThrowIfNull<T>(T, String)
  nameWithType: Utilities.ThrowIfNull<T>(T, String)
  fullName: Google.Apis.Util.Utilities.ThrowIfNull<T>(T, System.String)
  nameWithType.vb: Utilities.ThrowIfNull(Of T)(T, String)
  fullName.vb: Google.Apis.Util.Utilities.ThrowIfNull(Of T)(T, System.String)
  name.vb: ThrowIfNull(Of T)(T, String)
  spec.csharp:
  - uid: Google.Apis.Util.Utilities.ThrowIfNull``1(``0,System.String)
    name: ThrowIfNull<T>
    nameWithType: Utilities.ThrowIfNull<T>
    fullName: Google.Apis.Util.Utilities.ThrowIfNull<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Google.Apis.Util.Utilities.ThrowIfNull``1(``0,System.String)
    name: ThrowIfNull(Of T)
    nameWithType: Utilities.ThrowIfNull(Of T)
    fullName: Google.Apis.Util.Utilities.ThrowIfNull(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Google.Apis.Util.Utilities
  commentId: T:Google.Apis.Util.Utilities
  parent: Google.Apis.Util
  isExternal: false
  name: Utilities
  nameWithType: Utilities
  fullName: Google.Apis.Util.Utilities
- uid: Google.Apis.Util
  commentId: N:Google.Apis.Util
  isExternal: false
  name: Google.Apis.Util
  nameWithType: Google.Apis.Util
  fullName: Google.Apis.Util
- uid: Google.Apis.Http.ConfigurableHttpClient.MessageHandler*
  commentId: Overload:Google.Apis.Http.ConfigurableHttpClient.MessageHandler
  isExternal: false
  name: MessageHandler
  nameWithType: ConfigurableHttpClient.MessageHandler
  fullName: Google.Apis.Http.ConfigurableHttpClient.MessageHandler
- uid: Google.Apis.Http.ConfigurableHttpClient.#ctor*
  commentId: Overload:Google.Apis.Http.ConfigurableHttpClient.#ctor
  isExternal: false
  name: ConfigurableHttpClient
  nameWithType: ConfigurableHttpClient.ConfigurableHttpClient
  fullName: Google.Apis.Http.ConfigurableHttpClient.ConfigurableHttpClient
