### YamlMime:ManagedReference
items:
- uid: Google.Apis.Http.IConfigurableHttpClientInitializer
  commentId: T:Google.Apis.Http.IConfigurableHttpClientInitializer
  id: IConfigurableHttpClientInitializer
  parent: Google.Apis.Http
  children:
  - Google.Apis.Http.IConfigurableHttpClientInitializer.Initialize(Google.Apis.Http.ConfigurableHttpClient)
  langs:
  - csharp
  - vb
  name: IConfigurableHttpClientInitializer
  nameWithType: IConfigurableHttpClientInitializer
  fullName: Google.Apis.Http.IConfigurableHttpClientInitializer
  type: Interface
  source:
    remote:
      path: Src/Support/GoogleApis.Core/Apis/Http/IConfigurableHttpClientInitializer.cs
      branch: master
      repo: https://github.com/google/google-api-dotnet-client
    id: IConfigurableHttpClientInitializer
    path: Src/Support/GoogleApis.Core/Apis/Http/IConfigurableHttpClientInitializer.cs
    startLine: 29
  assemblies:
  - Google.Apis.Core
  namespace: Google.Apis.Http
  summary: "\nHTTP client initializer for changing the default behavior of HTTP client. \nUse this initializer to change default values like timeout and number of tries. \nYou can also set different handlers and interceptors like <xref href=\"Google.Apis.Http.IHttpUnsuccessfulResponseHandler\" data-throw-if-not-resolved=\"false\"></xref>s, \n<xref href=\"Google.Apis.Http.IHttpExceptionHandler\" data-throw-if-not-resolved=\"false\"></xref>s and <xref href=\"Google.Apis.Http.IHttpExecuteInterceptor\" data-throw-if-not-resolved=\"false\"></xref>s.\n"
  example: []
  syntax:
    content: public interface IConfigurableHttpClientInitializer
    content.vb: Public Interface IConfigurableHttpClientInitializer
  extensionMethods:
  - Google.Apis.Http.IConfigurableHttpClientInitializer.Google.Apis.Util.Utilities.ThrowIfNull``1(System.String)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Google.Apis.Http.IConfigurableHttpClientInitializer.Initialize(Google.Apis.Http.ConfigurableHttpClient)
  commentId: M:Google.Apis.Http.IConfigurableHttpClientInitializer.Initialize(Google.Apis.Http.ConfigurableHttpClient)
  id: Initialize(Google.Apis.Http.ConfigurableHttpClient)
  parent: Google.Apis.Http.IConfigurableHttpClientInitializer
  langs:
  - csharp
  - vb
  name: Initialize(ConfigurableHttpClient)
  nameWithType: IConfigurableHttpClientInitializer.Initialize(ConfigurableHttpClient)
  fullName: Google.Apis.Http.IConfigurableHttpClientInitializer.Initialize(Google.Apis.Http.ConfigurableHttpClient)
  type: Method
  source:
    remote:
      path: Src/Support/GoogleApis.Core/Apis/Http/IConfigurableHttpClientInitializer.cs
      branch: master
      repo: https://github.com/google/google-api-dotnet-client
    id: Initialize
    path: Src/Support/GoogleApis.Core/Apis/Http/IConfigurableHttpClientInitializer.cs
    startLine: 32
  assemblies:
  - Google.Apis.Core
  namespace: Google.Apis.Http
  summary: Initializes a HTTP client after it was created.
  example: []
  syntax:
    content: void Initialize(ConfigurableHttpClient httpClient)
    parameters:
    - id: httpClient
      type: Google.Apis.Http.ConfigurableHttpClient
    content.vb: Sub Initialize(httpClient As ConfigurableHttpClient)
  overload: Google.Apis.Http.IConfigurableHttpClientInitializer.Initialize*
references:
- uid: Google.Apis.Http.IHttpUnsuccessfulResponseHandler
  commentId: T:Google.Apis.Http.IHttpUnsuccessfulResponseHandler
  parent: Google.Apis.Http
  isExternal: false
  name: IHttpUnsuccessfulResponseHandler
  nameWithType: IHttpUnsuccessfulResponseHandler
  fullName: Google.Apis.Http.IHttpUnsuccessfulResponseHandler
- uid: Google.Apis.Http.IHttpExceptionHandler
  commentId: T:Google.Apis.Http.IHttpExceptionHandler
  parent: Google.Apis.Http
  isExternal: false
  name: IHttpExceptionHandler
  nameWithType: IHttpExceptionHandler
  fullName: Google.Apis.Http.IHttpExceptionHandler
- uid: Google.Apis.Http.IHttpExecuteInterceptor
  commentId: T:Google.Apis.Http.IHttpExecuteInterceptor
  parent: Google.Apis.Http
  isExternal: false
  name: IHttpExecuteInterceptor
  nameWithType: IHttpExecuteInterceptor
  fullName: Google.Apis.Http.IHttpExecuteInterceptor
- uid: Google.Apis.Http
  commentId: N:Google.Apis.Http
  isExternal: false
  name: Google.Apis.Http
  nameWithType: Google.Apis.Http
  fullName: Google.Apis.Http
- uid: Google.Apis.Http.IConfigurableHttpClientInitializer.Google.Apis.Util.Utilities.ThrowIfNull``1(System.String)
  commentId: M:Google.Apis.Util.Utilities.ThrowIfNull``1(``0,System.String)
  parent: Google.Apis.Util.Utilities
  definition: Google.Apis.Util.Utilities.ThrowIfNull``1(``0,System.String)
  name: ThrowIfNull<IConfigurableHttpClientInitializer>(String)
  nameWithType: Utilities.ThrowIfNull<IConfigurableHttpClientInitializer>(String)
  fullName: Google.Apis.Util.Utilities.ThrowIfNull<Google.Apis.Http.IConfigurableHttpClientInitializer>(System.String)
  nameWithType.vb: Utilities.ThrowIfNull(Of IConfigurableHttpClientInitializer)(String)
  fullName.vb: Google.Apis.Util.Utilities.ThrowIfNull(Of Google.Apis.Http.IConfigurableHttpClientInitializer)(System.String)
  name.vb: ThrowIfNull(Of IConfigurableHttpClientInitializer)(String)
  spec.csharp:
  - uid: Google.Apis.Util.Utilities.ThrowIfNull``1(System.String)
    name: ThrowIfNull<IConfigurableHttpClientInitializer>
    nameWithType: Utilities.ThrowIfNull<IConfigurableHttpClientInitializer>
    fullName: Google.Apis.Util.Utilities.ThrowIfNull<Google.Apis.Http.IConfigurableHttpClientInitializer>
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Google.Apis.Util.Utilities.ThrowIfNull``1(System.String)
    name: ThrowIfNull(Of IConfigurableHttpClientInitializer)
    nameWithType: Utilities.ThrowIfNull(Of IConfigurableHttpClientInitializer)
    fullName: Google.Apis.Util.Utilities.ThrowIfNull(Of Google.Apis.Http.IConfigurableHttpClientInitializer)
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Google.Apis.Util.Utilities.ThrowIfNull``1(``0,System.String)
  commentId: M:Google.Apis.Util.Utilities.ThrowIfNull``1(``0,System.String)
  isExternal: true
  name: ThrowIfNull<T>(T, String)
  nameWithType: Utilities.ThrowIfNull<T>(T, String)
  fullName: Google.Apis.Util.Utilities.ThrowIfNull<T>(T, System.String)
  nameWithType.vb: Utilities.ThrowIfNull(Of T)(T, String)
  fullName.vb: Google.Apis.Util.Utilities.ThrowIfNull(Of T)(T, System.String)
  name.vb: ThrowIfNull(Of T)(T, String)
  spec.csharp:
  - uid: Google.Apis.Util.Utilities.ThrowIfNull``1(``0,System.String)
    name: ThrowIfNull<T>
    nameWithType: Utilities.ThrowIfNull<T>
    fullName: Google.Apis.Util.Utilities.ThrowIfNull<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Google.Apis.Util.Utilities.ThrowIfNull``1(``0,System.String)
    name: ThrowIfNull(Of T)
    nameWithType: Utilities.ThrowIfNull(Of T)
    fullName: Google.Apis.Util.Utilities.ThrowIfNull(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Google.Apis.Util.Utilities
  commentId: T:Google.Apis.Util.Utilities
  parent: Google.Apis.Util
  isExternal: false
  name: Utilities
  nameWithType: Utilities
  fullName: Google.Apis.Util.Utilities
- uid: Google.Apis.Util
  commentId: N:Google.Apis.Util
  isExternal: false
  name: Google.Apis.Util
  nameWithType: Google.Apis.Util
  fullName: Google.Apis.Util
- uid: Google.Apis.Http.IConfigurableHttpClientInitializer.Initialize*
  commentId: Overload:Google.Apis.Http.IConfigurableHttpClientInitializer.Initialize
  isExternal: false
  name: Initialize
  nameWithType: IConfigurableHttpClientInitializer.Initialize
  fullName: Google.Apis.Http.IConfigurableHttpClientInitializer.Initialize
- uid: Google.Apis.Http.ConfigurableHttpClient
  commentId: T:Google.Apis.Http.ConfigurableHttpClient
  parent: Google.Apis.Http
  isExternal: false
  name: ConfigurableHttpClient
  nameWithType: ConfigurableHttpClient
  fullName: Google.Apis.Http.ConfigurableHttpClient
