### YamlMime:ManagedReference
items:
- uid: Google.Api.Gax.BatchingSettings
  commentId: T:Google.Api.Gax.BatchingSettings
  id: BatchingSettings
  parent: Google.Api.Gax
  children:
  - Google.Api.Gax.BatchingSettings.#ctor(System.Nullable{System.Int64},System.Nullable{System.Int64},System.Nullable{System.TimeSpan})
  - Google.Api.Gax.BatchingSettings.ByteCountThreshold
  - Google.Api.Gax.BatchingSettings.DelayThreshold
  - Google.Api.Gax.BatchingSettings.ElementCountThreshold
  langs:
  - csharp
  - vb
  name: BatchingSettings
  nameWithType: BatchingSettings
  fullName: Google.Api.Gax.BatchingSettings
  type: Class
  source:
    remote:
      path: src/Google.Api.Gax/BatchingSettings.cs
      branch: master
      repo: https://github.com/googleapis/gax-dotnet
    id: BatchingSettings
    path: src/Google.Api.Gax/BatchingSettings.cs
    startLine: 15
  assemblies:
  - Google.Api.Gax
  namespace: Google.Api.Gax
  summary: "\nBatching settings used to specify the conditions under which a batch of data\nwill be further processed.\n"
  example: []
  syntax:
    content: public sealed class BatchingSettings
    content.vb: Public NotInheritable Class BatchingSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: Google.Api.Gax.BatchingSettings.#ctor(System.Nullable{System.Int64},System.Nullable{System.Int64},System.Nullable{System.TimeSpan})
  commentId: M:Google.Api.Gax.BatchingSettings.#ctor(System.Nullable{System.Int64},System.Nullable{System.Int64},System.Nullable{System.TimeSpan})
  id: '#ctor(System.Nullable{System.Int64},System.Nullable{System.Int64},System.Nullable{System.TimeSpan})'
  parent: Google.Api.Gax.BatchingSettings
  langs:
  - csharp
  - vb
  name: BatchingSettings(Nullable<Int64>, Nullable<Int64>, Nullable<TimeSpan>)
  nameWithType: BatchingSettings.BatchingSettings(Nullable<Int64>, Nullable<Int64>, Nullable<TimeSpan>)
  fullName: Google.Api.Gax.BatchingSettings.BatchingSettings(System.Nullable<System.Int64>, System.Nullable<System.Int64>, System.Nullable<System.TimeSpan>)
  type: Constructor
  source:
    remote:
      path: src/Google.Api.Gax/BatchingSettings.cs
      branch: master
      repo: https://github.com/googleapis/gax-dotnet
    id: .ctor
    path: src/Google.Api.Gax/BatchingSettings.cs
    startLine: 23
  assemblies:
  - Google.Api.Gax
  namespace: Google.Api.Gax
  summary: "\nCreates a new instance with the specified settings.\n"
  example: []
  syntax:
    content: public BatchingSettings(long? elementCountThreshold, long? byteCountThreshold, TimeSpan? delayThreshold)
    parameters:
    - id: elementCountThreshold
      type: System.Nullable{System.Int64}
      description: The element count above which further processing of a batch will occur.
    - id: byteCountThreshold
      type: System.Nullable{System.Int64}
      description: The byte count above which further processing of a batch will occur.
    - id: delayThreshold
      type: System.Nullable{System.TimeSpan}
      description: The batch lifetime above which further processing of a batch will occur.
    content.vb: Public Sub New(elementCountThreshold As Long?, byteCountThreshold As Long?, delayThreshold As TimeSpan?)
  overload: Google.Api.Gax.BatchingSettings.#ctor*
  nameWithType.vb: BatchingSettings.BatchingSettings(Nullable(Of Int64), Nullable(Of Int64), Nullable(Of TimeSpan))
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: Google.Api.Gax.BatchingSettings.BatchingSettings(System.Nullable(Of System.Int64), System.Nullable(Of System.Int64), System.Nullable(Of System.TimeSpan))
  name.vb: BatchingSettings(Nullable(Of Int64), Nullable(Of Int64), Nullable(Of TimeSpan))
- uid: Google.Api.Gax.BatchingSettings.ElementCountThreshold
  commentId: P:Google.Api.Gax.BatchingSettings.ElementCountThreshold
  id: ElementCountThreshold
  parent: Google.Api.Gax.BatchingSettings
  langs:
  - csharp
  - vb
  name: ElementCountThreshold
  nameWithType: BatchingSettings.ElementCountThreshold
  fullName: Google.Api.Gax.BatchingSettings.ElementCountThreshold
  type: Property
  source:
    remote:
      path: src/Google.Api.Gax/BatchingSettings.cs
      branch: master
      repo: https://github.com/googleapis/gax-dotnet
    id: ElementCountThreshold
    path: src/Google.Api.Gax/BatchingSettings.cs
    startLine: 34
  assemblies:
  - Google.Api.Gax
  namespace: Google.Api.Gax
  summary: "\nThe element count above which further processing of a batch will occur.\n"
  example: []
  syntax:
    content: public long? ElementCountThreshold { get; }
    parameters: []
    return:
      type: System.Nullable{System.Int64}
    content.vb: Public ReadOnly Property ElementCountThreshold As Long?
  overload: Google.Api.Gax.BatchingSettings.ElementCountThreshold*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Google.Api.Gax.BatchingSettings.ByteCountThreshold
  commentId: P:Google.Api.Gax.BatchingSettings.ByteCountThreshold
  id: ByteCountThreshold
  parent: Google.Api.Gax.BatchingSettings
  langs:
  - csharp
  - vb
  name: ByteCountThreshold
  nameWithType: BatchingSettings.ByteCountThreshold
  fullName: Google.Api.Gax.BatchingSettings.ByteCountThreshold
  type: Property
  source:
    remote:
      path: src/Google.Api.Gax/BatchingSettings.cs
      branch: master
      repo: https://github.com/googleapis/gax-dotnet
    id: ByteCountThreshold
    path: src/Google.Api.Gax/BatchingSettings.cs
    startLine: 39
  assemblies:
  - Google.Api.Gax
  namespace: Google.Api.Gax
  summary: "\nThe byte count above which further processing of a batch will occur.\n"
  example: []
  syntax:
    content: public long? ByteCountThreshold { get; }
    parameters: []
    return:
      type: System.Nullable{System.Int64}
    content.vb: Public ReadOnly Property ByteCountThreshold As Long?
  overload: Google.Api.Gax.BatchingSettings.ByteCountThreshold*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Google.Api.Gax.BatchingSettings.DelayThreshold
  commentId: P:Google.Api.Gax.BatchingSettings.DelayThreshold
  id: DelayThreshold
  parent: Google.Api.Gax.BatchingSettings
  langs:
  - csharp
  - vb
  name: DelayThreshold
  nameWithType: BatchingSettings.DelayThreshold
  fullName: Google.Api.Gax.BatchingSettings.DelayThreshold
  type: Property
  source:
    remote:
      path: src/Google.Api.Gax/BatchingSettings.cs
      branch: master
      repo: https://github.com/googleapis/gax-dotnet
    id: DelayThreshold
    path: src/Google.Api.Gax/BatchingSettings.cs
    startLine: 44
  assemblies:
  - Google.Api.Gax
  namespace: Google.Api.Gax
  summary: "\nThe batch lifetime above which further processing of a batch will occur.\n"
  example: []
  syntax:
    content: public TimeSpan? DelayThreshold { get; }
    parameters: []
    return:
      type: System.Nullable{System.TimeSpan}
    content.vb: Public ReadOnly Property DelayThreshold As TimeSpan?
  overload: Google.Api.Gax.BatchingSettings.DelayThreshold*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: Google.Api.Gax
  commentId: N:Google.Api.Gax
  isExternal: false
  name: Google.Api.Gax
  nameWithType: Google.Api.Gax
  fullName: Google.Api.Gax
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Google.Api.Gax.BatchingSettings.#ctor*
  commentId: Overload:Google.Api.Gax.BatchingSettings.#ctor
  isExternal: false
  name: BatchingSettings
  nameWithType: BatchingSettings.BatchingSettings
  fullName: Google.Api.Gax.BatchingSettings.BatchingSettings
- uid: System.Nullable{System.Int64}
  commentId: T:System.Nullable{System.Int64}
  parent: System
  definition: System.Nullable`1
  name: Nullable<Int64>
  nameWithType: Nullable<Int64>
  fullName: System.Nullable<System.Int64>
  nameWithType.vb: Nullable(Of Int64)
  fullName.vb: System.Nullable(Of System.Int64)
  name.vb: Nullable(Of Int64)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Int64
    name: Int64
    nameWithType: Int64
    fullName: System.Int64
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Int64
    name: Int64
    nameWithType: Int64
    fullName: System.Int64
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Nullable{System.TimeSpan}
  commentId: T:System.Nullable{System.TimeSpan}
  parent: System
  definition: System.Nullable`1
  name: Nullable<TimeSpan>
  nameWithType: Nullable<TimeSpan>
  fullName: System.Nullable<System.TimeSpan>
  nameWithType.vb: Nullable(Of TimeSpan)
  fullName.vb: System.Nullable(Of System.TimeSpan)
  name.vb: Nullable(Of TimeSpan)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.TimeSpan
    name: TimeSpan
    nameWithType: TimeSpan
    fullName: System.TimeSpan
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.TimeSpan
    name: TimeSpan
    nameWithType: TimeSpan
    fullName: System.TimeSpan
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Nullable`1
  commentId: T:System.Nullable`1
  isExternal: true
  name: Nullable<T>
  nameWithType: Nullable<T>
  fullName: System.Nullable<T>
  nameWithType.vb: Nullable(Of T)
  fullName.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Google.Api.Gax.BatchingSettings.ElementCountThreshold*
  commentId: Overload:Google.Api.Gax.BatchingSettings.ElementCountThreshold
  isExternal: false
  name: ElementCountThreshold
  nameWithType: BatchingSettings.ElementCountThreshold
  fullName: Google.Api.Gax.BatchingSettings.ElementCountThreshold
- uid: Google.Api.Gax.BatchingSettings.ByteCountThreshold*
  commentId: Overload:Google.Api.Gax.BatchingSettings.ByteCountThreshold
  isExternal: false
  name: ByteCountThreshold
  nameWithType: BatchingSettings.ByteCountThreshold
  fullName: Google.Api.Gax.BatchingSettings.ByteCountThreshold
- uid: Google.Api.Gax.BatchingSettings.DelayThreshold*
  commentId: Overload:Google.Api.Gax.BatchingSettings.DelayThreshold
  isExternal: false
  name: DelayThreshold
  nameWithType: BatchingSettings.DelayThreshold
  fullName: Google.Api.Gax.BatchingSettings.DelayThreshold
