### YamlMime:ManagedReference
items:
- uid: Google.Api.Gax.FlowControlSettings
  commentId: T:Google.Api.Gax.FlowControlSettings
  id: FlowControlSettings
  parent: Google.Api.Gax
  children:
  - Google.Api.Gax.FlowControlSettings.#ctor(System.Nullable{System.Int64},System.Nullable{System.Int64})
  - Google.Api.Gax.FlowControlSettings.MaxOutstandingByteCount
  - Google.Api.Gax.FlowControlSettings.MaxOutstandingElementCount
  langs:
  - csharp
  - vb
  name: FlowControlSettings
  nameWithType: FlowControlSettings
  fullName: Google.Api.Gax.FlowControlSettings
  type: Class
  source:
    remote:
      path: Google.Api.Gax/FlowControlSettings.cs
      branch: master
      repo: https://github.com/googleapis/gax-dotnet
    id: FlowControlSettings
    path: Google.Api.Gax/FlowControlSettings.cs
    startLine: 12
  assemblies:
  - Google.Api.Gax
  namespace: Google.Api.Gax
  summary: "\nSettings used to control data flow.\n"
  example: []
  syntax:
    content: public sealed class FlowControlSettings
    content.vb: Public NotInheritable Class FlowControlSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: Google.Api.Gax.FlowControlSettings.#ctor(System.Nullable{System.Int64},System.Nullable{System.Int64})
  commentId: M:Google.Api.Gax.FlowControlSettings.#ctor(System.Nullable{System.Int64},System.Nullable{System.Int64})
  id: '#ctor(System.Nullable{System.Int64},System.Nullable{System.Int64})'
  parent: Google.Api.Gax.FlowControlSettings
  langs:
  - csharp
  - vb
  name: FlowControlSettings(Nullable<Int64>, Nullable<Int64>)
  nameWithType: FlowControlSettings.FlowControlSettings(Nullable<Int64>, Nullable<Int64>)
  fullName: Google.Api.Gax.FlowControlSettings.FlowControlSettings(System.Nullable<System.Int64>, System.Nullable<System.Int64>)
  type: Constructor
  source:
    remote:
      path: Google.Api.Gax/FlowControlSettings.cs
      branch: master
      repo: https://github.com/googleapis/gax-dotnet
    id: .ctor
    path: Google.Api.Gax/FlowControlSettings.cs
    startLine: 21
  assemblies:
  - Google.Api.Gax
  namespace: Google.Api.Gax
  summary: "\nCreates a new instance with the specified settings.\n"
  example: []
  syntax:
    content: public FlowControlSettings(long? maxOutstandingElementCount, long? maxOutstandingByteCount)
    parameters:
    - id: maxOutstandingElementCount
      type: System.Nullable{System.Int64}
      description: >-
        The maximum number of elements that can be outstanding before data flow is restricted, or

        null if there is no specified limit.
    - id: maxOutstandingByteCount
      type: System.Nullable{System.Int64}
      description: >-
        The maximum number of bytes that can be outstanding before data flow is restricted, or

        null if there is no specified limit.
    content.vb: Public Sub New(maxOutstandingElementCount As Long?, maxOutstandingByteCount As Long?)
  overload: Google.Api.Gax.FlowControlSettings.#ctor*
  nameWithType.vb: FlowControlSettings.FlowControlSettings(Nullable(Of Int64), Nullable(Of Int64))
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: Google.Api.Gax.FlowControlSettings.FlowControlSettings(System.Nullable(Of System.Int64), System.Nullable(Of System.Int64))
  name.vb: FlowControlSettings(Nullable(Of Int64), Nullable(Of Int64))
- uid: Google.Api.Gax.FlowControlSettings.MaxOutstandingElementCount
  commentId: P:Google.Api.Gax.FlowControlSettings.MaxOutstandingElementCount
  id: MaxOutstandingElementCount
  parent: Google.Api.Gax.FlowControlSettings
  langs:
  - csharp
  - vb
  name: MaxOutstandingElementCount
  nameWithType: FlowControlSettings.MaxOutstandingElementCount
  fullName: Google.Api.Gax.FlowControlSettings.MaxOutstandingElementCount
  type: Property
  source:
    remote:
      path: Google.Api.Gax/FlowControlSettings.cs
      branch: master
      repo: https://github.com/googleapis/gax-dotnet
    id: MaxOutstandingElementCount
    path: Google.Api.Gax/FlowControlSettings.cs
    startLine: 31
  assemblies:
  - Google.Api.Gax
  namespace: Google.Api.Gax
  summary: "\nThe maximum number of elements that can be outstanding before data flow is restricted, or\nnull if there is no specified limit.\n"
  example: []
  syntax:
    content: public long? MaxOutstandingElementCount { get; }
    parameters: []
    return:
      type: System.Nullable{System.Int64}
    content.vb: Public ReadOnly Property MaxOutstandingElementCount As Long?
  overload: Google.Api.Gax.FlowControlSettings.MaxOutstandingElementCount*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Google.Api.Gax.FlowControlSettings.MaxOutstandingByteCount
  commentId: P:Google.Api.Gax.FlowControlSettings.MaxOutstandingByteCount
  id: MaxOutstandingByteCount
  parent: Google.Api.Gax.FlowControlSettings
  langs:
  - csharp
  - vb
  name: MaxOutstandingByteCount
  nameWithType: FlowControlSettings.MaxOutstandingByteCount
  fullName: Google.Api.Gax.FlowControlSettings.MaxOutstandingByteCount
  type: Property
  source:
    remote:
      path: Google.Api.Gax/FlowControlSettings.cs
      branch: master
      repo: https://github.com/googleapis/gax-dotnet
    id: MaxOutstandingByteCount
    path: Google.Api.Gax/FlowControlSettings.cs
    startLine: 37
  assemblies:
  - Google.Api.Gax
  namespace: Google.Api.Gax
  summary: "\nThe maximum number of bytes that can be outstanding before data flow is restricted, or\nnull if there is no specified limit.\n"
  example: []
  syntax:
    content: public long? MaxOutstandingByteCount { get; }
    parameters: []
    return:
      type: System.Nullable{System.Int64}
    content.vb: Public ReadOnly Property MaxOutstandingByteCount As Long?
  overload: Google.Api.Gax.FlowControlSettings.MaxOutstandingByteCount*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: Google.Api.Gax
  commentId: N:Google.Api.Gax
  name: Google.Api.Gax
  nameWithType: Google.Api.Gax
  fullName: Google.Api.Gax
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Google.Api.Gax.FlowControlSettings.#ctor*
  commentId: Overload:Google.Api.Gax.FlowControlSettings.#ctor
  name: FlowControlSettings
  nameWithType: FlowControlSettings.FlowControlSettings
  fullName: Google.Api.Gax.FlowControlSettings.FlowControlSettings
- uid: System.Nullable{System.Int64}
  commentId: T:System.Nullable{System.Int64}
  parent: System
  definition: System.Nullable`1
  name: Nullable<Int64>
  nameWithType: Nullable<Int64>
  fullName: System.Nullable<System.Int64>
  nameWithType.vb: Nullable(Of Int64)
  fullName.vb: System.Nullable(Of System.Int64)
  name.vb: Nullable(Of Int64)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Int64
    name: Int64
    nameWithType: Int64
    fullName: System.Int64
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Int64
    name: Int64
    nameWithType: Int64
    fullName: System.Int64
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Nullable`1
  commentId: T:System.Nullable`1
  isExternal: true
  name: Nullable<T>
  nameWithType: Nullable<T>
  fullName: System.Nullable<T>
  nameWithType.vb: Nullable(Of T)
  fullName.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Google.Api.Gax.FlowControlSettings.MaxOutstandingElementCount*
  commentId: Overload:Google.Api.Gax.FlowControlSettings.MaxOutstandingElementCount
  name: MaxOutstandingElementCount
  nameWithType: FlowControlSettings.MaxOutstandingElementCount
  fullName: Google.Api.Gax.FlowControlSettings.MaxOutstandingElementCount
- uid: Google.Api.Gax.FlowControlSettings.MaxOutstandingByteCount*
  commentId: Overload:Google.Api.Gax.FlowControlSettings.MaxOutstandingByteCount
  name: MaxOutstandingByteCount
  nameWithType: FlowControlSettings.MaxOutstandingByteCount
  fullName: Google.Api.Gax.FlowControlSettings.MaxOutstandingByteCount
