### YamlMime:ManagedReference
items:
- uid: Google.Apis.Bigquery.v2.Data.JobConfiguration
  commentId: T:Google.Apis.Bigquery.v2.Data.JobConfiguration
  id: JobConfiguration
  parent: Google.Apis.Bigquery.v2.Data
  children:
  - Google.Apis.Bigquery.v2.Data.JobConfiguration.Copy
  - Google.Apis.Bigquery.v2.Data.JobConfiguration.DryRun
  - Google.Apis.Bigquery.v2.Data.JobConfiguration.ETag
  - Google.Apis.Bigquery.v2.Data.JobConfiguration.Extract
  - Google.Apis.Bigquery.v2.Data.JobConfiguration.Labels
  - Google.Apis.Bigquery.v2.Data.JobConfiguration.Load
  - Google.Apis.Bigquery.v2.Data.JobConfiguration.Query
  langs:
  - csharp
  - vb
  name: JobConfiguration
  nameWithType: JobConfiguration
  fullName: Google.Apis.Bigquery.v2.Data.JobConfiguration
  type: Class
  source:
    remote:
      path: Src/Generated/Google.Apis.Bigquery.v2/Google.Apis.Bigquery.v2.cs
      branch: master
      repo: https://github.com/google/google-api-dotnet-client
    id: JobConfiguration
    path: Src/Generated/Google.Apis.Bigquery.v2/Google.Apis.Bigquery.v2.cs
    startLine: 3100
  assemblies:
  - Google.Apis.Bigquery.v2
  namespace: Google.Apis.Bigquery.v2.Data
  syntax:
    content: 'public class JobConfiguration : Requests.IDirectResponseSchema'
    content.vb: >-
      Public Class JobConfiguration
          Inherits Requests.IDirectResponseSchema
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Google.Apis.Bigquery.v2.Data.JobConfiguration.Copy
  commentId: P:Google.Apis.Bigquery.v2.Data.JobConfiguration.Copy
  id: Copy
  parent: Google.Apis.Bigquery.v2.Data.JobConfiguration
  langs:
  - csharp
  - vb
  name: Copy
  nameWithType: JobConfiguration.Copy
  fullName: Google.Apis.Bigquery.v2.Data.JobConfiguration.Copy
  type: Property
  source:
    remote:
      path: Src/Generated/Google.Apis.Bigquery.v2/Google.Apis.Bigquery.v2.cs
      branch: master
      repo: https://github.com/google/google-api-dotnet-client
    id: Copy
    path: Src/Generated/Google.Apis.Bigquery.v2/Google.Apis.Bigquery.v2.cs
    startLine: 3103
  assemblies:
  - Google.Apis.Bigquery.v2
  namespace: Google.Apis.Bigquery.v2.Data
  summary: '[Pick one] Copies a table.'
  example: []
  syntax:
    content: public virtual JobConfigurationTableCopy Copy { get; set; }
    parameters: []
    return:
      type: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy
    content.vb: Public Overridable Property Copy As JobConfigurationTableCopy
  overload: Google.Apis.Bigquery.v2.Data.JobConfiguration.Copy*
  modifiers.csharp:
  - public
  - virtual
  - get
  - set
  modifiers.vb:
  - Public
  - Overridable
- uid: Google.Apis.Bigquery.v2.Data.JobConfiguration.DryRun
  commentId: P:Google.Apis.Bigquery.v2.Data.JobConfiguration.DryRun
  id: DryRun
  parent: Google.Apis.Bigquery.v2.Data.JobConfiguration
  langs:
  - csharp
  - vb
  name: DryRun
  nameWithType: JobConfiguration.DryRun
  fullName: Google.Apis.Bigquery.v2.Data.JobConfiguration.DryRun
  type: Property
  source:
    remote:
      path: Src/Generated/Google.Apis.Bigquery.v2/Google.Apis.Bigquery.v2.cs
      branch: master
      repo: https://github.com/google/google-api-dotnet-client
    id: DryRun
    path: Src/Generated/Google.Apis.Bigquery.v2/Google.Apis.Bigquery.v2.cs
    startLine: 3109
  assemblies:
  - Google.Apis.Bigquery.v2
  namespace: Google.Apis.Bigquery.v2.Data
  summary: >-
    [Optional] If set, don't actually run this job. A valid query will return a mostly empty response

    with some processing statistics, while an invalid query will return the same error it would if it wasn't a

    dry run. Behavior of non-query jobs is undefined.
  example: []
  syntax:
    content: public virtual System.Nullable<bool> DryRun { get; set; }
    parameters: []
    return:
      type: System.Nullable{System.Boolean}
    content.vb: Public Overridable Property DryRun As System.Nullable(Of Boolean)
  overload: Google.Apis.Bigquery.v2.Data.JobConfiguration.DryRun*
  modifiers.csharp:
  - public
  - virtual
  - get
  - set
  modifiers.vb:
  - Public
  - Overridable
- uid: Google.Apis.Bigquery.v2.Data.JobConfiguration.Extract
  commentId: P:Google.Apis.Bigquery.v2.Data.JobConfiguration.Extract
  id: Extract
  parent: Google.Apis.Bigquery.v2.Data.JobConfiguration
  langs:
  - csharp
  - vb
  name: Extract
  nameWithType: JobConfiguration.Extract
  fullName: Google.Apis.Bigquery.v2.Data.JobConfiguration.Extract
  type: Property
  source:
    remote:
      path: Src/Generated/Google.Apis.Bigquery.v2/Google.Apis.Bigquery.v2.cs
      branch: master
      repo: https://github.com/google/google-api-dotnet-client
    id: Extract
    path: Src/Generated/Google.Apis.Bigquery.v2/Google.Apis.Bigquery.v2.cs
    startLine: 3113
  assemblies:
  - Google.Apis.Bigquery.v2
  namespace: Google.Apis.Bigquery.v2.Data
  summary: '[Pick one] Configures an extract job.'
  example: []
  syntax:
    content: public virtual JobConfigurationExtract Extract { get; set; }
    parameters: []
    return:
      type: Google.Apis.Bigquery.v2.Data.JobConfigurationExtract
    content.vb: Public Overridable Property Extract As JobConfigurationExtract
  overload: Google.Apis.Bigquery.v2.Data.JobConfiguration.Extract*
  modifiers.csharp:
  - public
  - virtual
  - get
  - set
  modifiers.vb:
  - Public
  - Overridable
- uid: Google.Apis.Bigquery.v2.Data.JobConfiguration.Labels
  commentId: P:Google.Apis.Bigquery.v2.Data.JobConfiguration.Labels
  id: Labels
  parent: Google.Apis.Bigquery.v2.Data.JobConfiguration
  langs:
  - csharp
  - vb
  name: Labels
  nameWithType: JobConfiguration.Labels
  fullName: Google.Apis.Bigquery.v2.Data.JobConfiguration.Labels
  type: Property
  source:
    remote:
      path: Src/Generated/Google.Apis.Bigquery.v2/Google.Apis.Bigquery.v2.cs
      branch: master
      repo: https://github.com/google/google-api-dotnet-client
    id: Labels
    path: Src/Generated/Google.Apis.Bigquery.v2/Google.Apis.Bigquery.v2.cs
    startLine: 3120
  assemblies:
  - Google.Apis.Bigquery.v2
  namespace: Google.Apis.Bigquery.v2.Data
  summary: >-
    [Experimental] The labels associated with this job. You can use these to organize and group your

    jobs. Label keys and values can be no longer than 63 characters, can only contain lowercase letters, numeric

    characters, underscores and dashes. International characters are allowed. Label values are optional. Label

    keys must start with a letter and each label in the list must have a different key.
  example: []
  syntax:
    content: public virtual System.Collections.Generic.IDictionary<string, string> Labels { get; set; }
    parameters: []
    return:
      type: System.Collections.Generic.IDictionary{System.String,System.String}
    content.vb: Public Overridable Property Labels As System.Collections.Generic.IDictionary(Of String, String)
  overload: Google.Apis.Bigquery.v2.Data.JobConfiguration.Labels*
  modifiers.csharp:
  - public
  - virtual
  - get
  - set
  modifiers.vb:
  - Public
  - Overridable
- uid: Google.Apis.Bigquery.v2.Data.JobConfiguration.Load
  commentId: P:Google.Apis.Bigquery.v2.Data.JobConfiguration.Load
  id: Load
  parent: Google.Apis.Bigquery.v2.Data.JobConfiguration
  langs:
  - csharp
  - vb
  name: Load
  nameWithType: JobConfiguration.Load
  fullName: Google.Apis.Bigquery.v2.Data.JobConfiguration.Load
  type: Property
  source:
    remote:
      path: Src/Generated/Google.Apis.Bigquery.v2/Google.Apis.Bigquery.v2.cs
      branch: master
      repo: https://github.com/google/google-api-dotnet-client
    id: Load
    path: Src/Generated/Google.Apis.Bigquery.v2/Google.Apis.Bigquery.v2.cs
    startLine: 3124
  assemblies:
  - Google.Apis.Bigquery.v2
  namespace: Google.Apis.Bigquery.v2.Data
  summary: '[Pick one] Configures a load job.'
  example: []
  syntax:
    content: public virtual JobConfigurationLoad Load { get; set; }
    parameters: []
    return:
      type: Google.Apis.Bigquery.v2.Data.JobConfigurationLoad
    content.vb: Public Overridable Property Load As JobConfigurationLoad
  overload: Google.Apis.Bigquery.v2.Data.JobConfiguration.Load*
  modifiers.csharp:
  - public
  - virtual
  - get
  - set
  modifiers.vb:
  - Public
  - Overridable
- uid: Google.Apis.Bigquery.v2.Data.JobConfiguration.Query
  commentId: P:Google.Apis.Bigquery.v2.Data.JobConfiguration.Query
  id: Query
  parent: Google.Apis.Bigquery.v2.Data.JobConfiguration
  langs:
  - csharp
  - vb
  name: Query
  nameWithType: JobConfiguration.Query
  fullName: Google.Apis.Bigquery.v2.Data.JobConfiguration.Query
  type: Property
  source:
    remote:
      path: Src/Generated/Google.Apis.Bigquery.v2/Google.Apis.Bigquery.v2.cs
      branch: master
      repo: https://github.com/google/google-api-dotnet-client
    id: Query
    path: Src/Generated/Google.Apis.Bigquery.v2/Google.Apis.Bigquery.v2.cs
    startLine: 3128
  assemblies:
  - Google.Apis.Bigquery.v2
  namespace: Google.Apis.Bigquery.v2.Data
  summary: '[Pick one] Configures a query job.'
  example: []
  syntax:
    content: public virtual JobConfigurationQuery Query { get; set; }
    parameters: []
    return:
      type: Google.Apis.Bigquery.v2.Data.JobConfigurationQuery
    content.vb: Public Overridable Property Query As JobConfigurationQuery
  overload: Google.Apis.Bigquery.v2.Data.JobConfiguration.Query*
  modifiers.csharp:
  - public
  - virtual
  - get
  - set
  modifiers.vb:
  - Public
  - Overridable
- uid: Google.Apis.Bigquery.v2.Data.JobConfiguration.ETag
  commentId: P:Google.Apis.Bigquery.v2.Data.JobConfiguration.ETag
  id: ETag
  parent: Google.Apis.Bigquery.v2.Data.JobConfiguration
  langs:
  - csharp
  - vb
  name: ETag
  nameWithType: JobConfiguration.ETag
  fullName: Google.Apis.Bigquery.v2.Data.JobConfiguration.ETag
  type: Property
  source:
    remote:
      path: Src/Generated/Google.Apis.Bigquery.v2/Google.Apis.Bigquery.v2.cs
      branch: master
      repo: https://github.com/google/google-api-dotnet-client
    id: ETag
    path: Src/Generated/Google.Apis.Bigquery.v2/Google.Apis.Bigquery.v2.cs
    startLine: 3132
  assemblies:
  - Google.Apis.Bigquery.v2
  namespace: Google.Apis.Bigquery.v2.Data
  summary: The ETag of the item.
  example: []
  syntax:
    content: public virtual string ETag { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Overridable Property ETag As String
  overload: Google.Apis.Bigquery.v2.Data.JobConfiguration.ETag*
  modifiers.csharp:
  - public
  - virtual
  - get
  - set
  modifiers.vb:
  - Public
  - Overridable
references:
- uid: Google.Apis.Bigquery.v2.Data
  commentId: N:Google.Apis.Bigquery.v2.Data
  isExternal: false
  name: Google.Apis.Bigquery.v2.Data
  nameWithType: Google.Apis.Bigquery.v2.Data
  fullName: Google.Apis.Bigquery.v2.Data
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Google.Apis.Bigquery.v2.Data.JobConfiguration.Copy*
  commentId: Overload:Google.Apis.Bigquery.v2.Data.JobConfiguration.Copy
  isExternal: false
  name: Copy
  nameWithType: JobConfiguration.Copy
  fullName: Google.Apis.Bigquery.v2.Data.JobConfiguration.Copy
- uid: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy
  commentId: T:Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy
  parent: Google.Apis.Bigquery.v2.Data
  isExternal: false
  name: JobConfigurationTableCopy
  nameWithType: JobConfigurationTableCopy
  fullName: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy
- uid: Google.Apis.Bigquery.v2.Data.JobConfiguration.DryRun*
  commentId: Overload:Google.Apis.Bigquery.v2.Data.JobConfiguration.DryRun
  isExternal: false
  name: DryRun
  nameWithType: JobConfiguration.DryRun
  fullName: Google.Apis.Bigquery.v2.Data.JobConfiguration.DryRun
- uid: System.Nullable{System.Boolean}
  commentId: '!:System.Nullable{System.Boolean}'
  definition: System.Nullable`1
  name: System.Nullable<Boolean>
  nameWithType: System.Nullable<Boolean>
  fullName: System.Nullable<System.Boolean>
  nameWithType.vb: System.Nullable(Of Boolean)
  fullName.vb: System.Nullable(Of System.Boolean)
  name.vb: System.Nullable(Of Boolean)
  spec.csharp:
  - uid: System.Nullable`1
    name: System.Nullable
    nameWithType: System.Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Boolean
    name: Boolean
    nameWithType: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: System.Nullable
    nameWithType: System.Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Boolean
    name: Boolean
    nameWithType: Boolean
    fullName: System.Boolean
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Nullable`1
  isExternal: true
  name: System.Nullable<>
  nameWithType: System.Nullable<>
  fullName: System.Nullable<>
  nameWithType.vb: System.Nullable(Of )
  fullName.vb: System.Nullable(Of )
  name.vb: System.Nullable(Of )
  spec.csharp:
  - uid: System.Nullable`1
    name: System.Nullable
    nameWithType: System.Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: System.Nullable
    nameWithType: System.Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: Google.Apis.Bigquery.v2.Data.JobConfiguration.Extract*
  commentId: Overload:Google.Apis.Bigquery.v2.Data.JobConfiguration.Extract
  isExternal: false
  name: Extract
  nameWithType: JobConfiguration.Extract
  fullName: Google.Apis.Bigquery.v2.Data.JobConfiguration.Extract
- uid: Google.Apis.Bigquery.v2.Data.JobConfigurationExtract
  commentId: T:Google.Apis.Bigquery.v2.Data.JobConfigurationExtract
  parent: Google.Apis.Bigquery.v2.Data
  isExternal: false
  name: JobConfigurationExtract
  nameWithType: JobConfigurationExtract
  fullName: Google.Apis.Bigquery.v2.Data.JobConfigurationExtract
- uid: Google.Apis.Bigquery.v2.Data.JobConfiguration.Labels*
  commentId: Overload:Google.Apis.Bigquery.v2.Data.JobConfiguration.Labels
  isExternal: false
  name: Labels
  nameWithType: JobConfiguration.Labels
  fullName: Google.Apis.Bigquery.v2.Data.JobConfiguration.Labels
- uid: System.Collections.Generic.IDictionary{System.String,System.String}
  commentId: '!:System.Collections.Generic.IDictionary{System.String,System.String}'
  definition: System.Collections.Generic.IDictionary`2
  name: System.Collections.Generic.IDictionary<String, String>
  nameWithType: System.Collections.Generic.IDictionary<String, String>
  fullName: System.Collections.Generic.IDictionary<System.String, System.String>
  nameWithType.vb: System.Collections.Generic.IDictionary(Of String, String)
  fullName.vb: System.Collections.Generic.IDictionary(Of System.String, System.String)
  name.vb: System.Collections.Generic.IDictionary(Of String, String)
  spec.csharp:
  - uid: System.Collections.Generic.IDictionary`2
    name: System.Collections.Generic.IDictionary
    nameWithType: System.Collections.Generic.IDictionary
    fullName: System.Collections.Generic.IDictionary
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IDictionary`2
    name: System.Collections.Generic.IDictionary
    nameWithType: System.Collections.Generic.IDictionary
    fullName: System.Collections.Generic.IDictionary
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.IDictionary`2
  isExternal: true
  name: System.Collections.Generic.IDictionary<, >
  nameWithType: System.Collections.Generic.IDictionary<, >
  fullName: System.Collections.Generic.IDictionary<, >
  nameWithType.vb: System.Collections.Generic.IDictionary(Of , )
  fullName.vb: System.Collections.Generic.IDictionary(Of , )
  name.vb: System.Collections.Generic.IDictionary(Of , )
  spec.csharp:
  - uid: System.Collections.Generic.IDictionary`2
    name: System.Collections.Generic.IDictionary
    nameWithType: System.Collections.Generic.IDictionary
    fullName: System.Collections.Generic.IDictionary
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IDictionary`2
    name: System.Collections.Generic.IDictionary
    nameWithType: System.Collections.Generic.IDictionary
    fullName: System.Collections.Generic.IDictionary
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: Google.Apis.Bigquery.v2.Data.JobConfiguration.Load*
  commentId: Overload:Google.Apis.Bigquery.v2.Data.JobConfiguration.Load
  isExternal: false
  name: Load
  nameWithType: JobConfiguration.Load
  fullName: Google.Apis.Bigquery.v2.Data.JobConfiguration.Load
- uid: Google.Apis.Bigquery.v2.Data.JobConfigurationLoad
  commentId: T:Google.Apis.Bigquery.v2.Data.JobConfigurationLoad
  parent: Google.Apis.Bigquery.v2.Data
  isExternal: false
  name: JobConfigurationLoad
  nameWithType: JobConfigurationLoad
  fullName: Google.Apis.Bigquery.v2.Data.JobConfigurationLoad
- uid: Google.Apis.Bigquery.v2.Data.JobConfiguration.Query*
  commentId: Overload:Google.Apis.Bigquery.v2.Data.JobConfiguration.Query
  isExternal: false
  name: Query
  nameWithType: JobConfiguration.Query
  fullName: Google.Apis.Bigquery.v2.Data.JobConfiguration.Query
- uid: Google.Apis.Bigquery.v2.Data.JobConfigurationQuery
  commentId: T:Google.Apis.Bigquery.v2.Data.JobConfigurationQuery
  parent: Google.Apis.Bigquery.v2.Data
  isExternal: false
  name: JobConfigurationQuery
  nameWithType: JobConfigurationQuery
  fullName: Google.Apis.Bigquery.v2.Data.JobConfigurationQuery
- uid: Google.Apis.Bigquery.v2.Data.JobConfiguration.ETag*
  commentId: Overload:Google.Apis.Bigquery.v2.Data.JobConfiguration.ETag
  isExternal: false
  name: ETag
  nameWithType: JobConfiguration.ETag
  fullName: Google.Apis.Bigquery.v2.Data.JobConfiguration.ETag
- uid: System.String
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
