### YamlMime:ManagedReference
items:
- uid: Google.Apis.Bigquery.v2.Data.EncryptionConfiguration
  commentId: T:Google.Apis.Bigquery.v2.Data.EncryptionConfiguration
  id: EncryptionConfiguration
  parent: Google.Apis.Bigquery.v2.Data
  children:
  - Google.Apis.Bigquery.v2.Data.EncryptionConfiguration.ETag
  - Google.Apis.Bigquery.v2.Data.EncryptionConfiguration.KmsKeyName
  langs:
  - csharp
  - vb
  name: EncryptionConfiguration
  nameWithType: EncryptionConfiguration
  fullName: Google.Apis.Bigquery.v2.Data.EncryptionConfiguration
  type: Class
  source:
    remote:
      path: Src/Generated/Google.Apis.Bigquery.v2/Google.Apis.Bigquery.v2.cs
      branch: master
      repo: https://github.com/google/google-api-dotnet-client
    id: EncryptionConfiguration
    path: Src/Generated/Google.Apis.Bigquery.v2/Google.Apis.Bigquery.v2.cs
    startLine: 2864
  assemblies:
  - Google.Apis.Bigquery.v2
  namespace: Google.Apis.Bigquery.v2.Data
  syntax:
    content: 'public class EncryptionConfiguration : Requests.IDirectResponseSchema'
    content.vb: >-
      Public Class EncryptionConfiguration
          Inherits Requests.IDirectResponseSchema
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Google.Apis.Bigquery.v2.Data.EncryptionConfiguration.KmsKeyName
  commentId: P:Google.Apis.Bigquery.v2.Data.EncryptionConfiguration.KmsKeyName
  id: KmsKeyName
  parent: Google.Apis.Bigquery.v2.Data.EncryptionConfiguration
  langs:
  - csharp
  - vb
  name: KmsKeyName
  nameWithType: EncryptionConfiguration.KmsKeyName
  fullName: Google.Apis.Bigquery.v2.Data.EncryptionConfiguration.KmsKeyName
  type: Property
  source:
    remote:
      path: Src/Generated/Google.Apis.Bigquery.v2/Google.Apis.Bigquery.v2.cs
      branch: master
      repo: https://github.com/google/google-api-dotnet-client
    id: KmsKeyName
    path: Src/Generated/Google.Apis.Bigquery.v2/Google.Apis.Bigquery.v2.cs
    startLine: 2869
  assemblies:
  - Google.Apis.Bigquery.v2
  namespace: Google.Apis.Bigquery.v2.Data
  summary: >-
    [Optional] Describes the Cloud KMS encryption key that will be used to protect destination BigQuery

    table. The BigQuery Service Account associated with your project requires access to this encryption

    key.
  example: []
  syntax:
    content: public virtual string KmsKeyName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Overridable Property KmsKeyName As String
  overload: Google.Apis.Bigquery.v2.Data.EncryptionConfiguration.KmsKeyName*
  modifiers.csharp:
  - public
  - virtual
  - get
  - set
  modifiers.vb:
  - Public
  - Overridable
- uid: Google.Apis.Bigquery.v2.Data.EncryptionConfiguration.ETag
  commentId: P:Google.Apis.Bigquery.v2.Data.EncryptionConfiguration.ETag
  id: ETag
  parent: Google.Apis.Bigquery.v2.Data.EncryptionConfiguration
  langs:
  - csharp
  - vb
  name: ETag
  nameWithType: EncryptionConfiguration.ETag
  fullName: Google.Apis.Bigquery.v2.Data.EncryptionConfiguration.ETag
  type: Property
  source:
    remote:
      path: Src/Generated/Google.Apis.Bigquery.v2/Google.Apis.Bigquery.v2.cs
      branch: master
      repo: https://github.com/google/google-api-dotnet-client
    id: ETag
    path: Src/Generated/Google.Apis.Bigquery.v2/Google.Apis.Bigquery.v2.cs
    startLine: 2873
  assemblies:
  - Google.Apis.Bigquery.v2
  namespace: Google.Apis.Bigquery.v2.Data
  summary: The ETag of the item.
  example: []
  syntax:
    content: public virtual string ETag { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Overridable Property ETag As String
  overload: Google.Apis.Bigquery.v2.Data.EncryptionConfiguration.ETag*
  modifiers.csharp:
  - public
  - virtual
  - get
  - set
  modifiers.vb:
  - Public
  - Overridable
references:
- uid: Google.Apis.Bigquery.v2.Data
  commentId: N:Google.Apis.Bigquery.v2.Data
  isExternal: false
  name: Google.Apis.Bigquery.v2.Data
  nameWithType: Google.Apis.Bigquery.v2.Data
  fullName: Google.Apis.Bigquery.v2.Data
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Google.Apis.Bigquery.v2.Data.EncryptionConfiguration.KmsKeyName*
  commentId: Overload:Google.Apis.Bigquery.v2.Data.EncryptionConfiguration.KmsKeyName
  isExternal: false
  name: KmsKeyName
  nameWithType: EncryptionConfiguration.KmsKeyName
  fullName: Google.Apis.Bigquery.v2.Data.EncryptionConfiguration.KmsKeyName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Google.Apis.Bigquery.v2.Data.EncryptionConfiguration.ETag*
  commentId: Overload:Google.Apis.Bigquery.v2.Data.EncryptionConfiguration.ETag
  isExternal: false
  name: ETag
  nameWithType: EncryptionConfiguration.ETag
  fullName: Google.Apis.Bigquery.v2.Data.EncryptionConfiguration.ETag
