### YamlMime:ManagedReference
items:
- uid: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy
  commentId: T:Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy
  id: JobConfigurationTableCopy
  parent: Google.Apis.Bigquery.v2.Data
  children:
  - Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.CreateDisposition
  - Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.DestinationEncryptionConfiguration
  - Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.DestinationTable
  - Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.ETag
  - Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.SourceTable
  - Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.SourceTables
  - Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.WriteDisposition
  langs:
  - csharp
  - vb
  name: JobConfigurationTableCopy
  nameWithType: JobConfigurationTableCopy
  fullName: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy
  type: Class
  source:
    remote:
      path: Src/Generated/Google.Apis.Bigquery.v2/Google.Apis.Bigquery.v2.cs
      branch: master
      repo: https://github.com/google/google-api-dotnet-client
    id: JobConfigurationTableCopy
    path: Src/Generated/Google.Apis.Bigquery.v2/Google.Apis.Bigquery.v2.cs
    startLine: 3573
  assemblies:
  - Google.Apis.Bigquery.v2
  namespace: Google.Apis.Bigquery.v2.Data
  syntax:
    content: 'public class JobConfigurationTableCopy : Requests.IDirectResponseSchema'
    content.vb: >-
      Public Class JobConfigurationTableCopy
          Inherits Requests.IDirectResponseSchema
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.CreateDisposition
  commentId: P:Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.CreateDisposition
  id: CreateDisposition
  parent: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy
  langs:
  - csharp
  - vb
  name: CreateDisposition
  nameWithType: JobConfigurationTableCopy.CreateDisposition
  fullName: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.CreateDisposition
  type: Property
  source:
    remote:
      path: Src/Generated/Google.Apis.Bigquery.v2/Google.Apis.Bigquery.v2.cs
      branch: master
      repo: https://github.com/google/google-api-dotnet-client
    id: CreateDisposition
    path: Src/Generated/Google.Apis.Bigquery.v2/Google.Apis.Bigquery.v2.cs
    startLine: 3580
  assemblies:
  - Google.Apis.Bigquery.v2
  namespace: Google.Apis.Bigquery.v2.Data
  summary: >-
    [Optional] Specifies whether the job is allowed to create new tables. The following values are

    supported: CREATE_IF_NEEDED: If the table does not exist, BigQuery creates the table. CREATE_NEVER: The

    table must already exist. If it does not, a &apos;notFound&apos; error is returned in the job result. The default

    value is CREATE_IF_NEEDED. Creation, truncation and append actions occur as one atomic update upon job

    completion.
  example: []
  syntax:
    content: public virtual string CreateDisposition { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Overridable Property CreateDisposition As String
  overload: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.CreateDisposition*
  modifiers.csharp:
  - public
  - virtual
  - get
  - set
  modifiers.vb:
  - Public
  - Overridable
- uid: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.DestinationEncryptionConfiguration
  commentId: P:Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.DestinationEncryptionConfiguration
  id: DestinationEncryptionConfiguration
  parent: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy
  langs:
  - csharp
  - vb
  name: DestinationEncryptionConfiguration
  nameWithType: JobConfigurationTableCopy.DestinationEncryptionConfiguration
  fullName: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.DestinationEncryptionConfiguration
  type: Property
  source:
    remote:
      path: Src/Generated/Google.Apis.Bigquery.v2/Google.Apis.Bigquery.v2.cs
      branch: master
      repo: https://github.com/google/google-api-dotnet-client
    id: DestinationEncryptionConfiguration
    path: Src/Generated/Google.Apis.Bigquery.v2/Google.Apis.Bigquery.v2.cs
    startLine: 3584
  assemblies:
  - Google.Apis.Bigquery.v2
  namespace: Google.Apis.Bigquery.v2.Data
  summary: '[Experimental] Custom encryption configuration (e.g., Cloud KMS keys).'
  example: []
  syntax:
    content: public virtual EncryptionConfiguration DestinationEncryptionConfiguration { get; set; }
    parameters: []
    return:
      type: Google.Apis.Bigquery.v2.Data.EncryptionConfiguration
    content.vb: Public Overridable Property DestinationEncryptionConfiguration As EncryptionConfiguration
  overload: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.DestinationEncryptionConfiguration*
  modifiers.csharp:
  - public
  - virtual
  - get
  - set
  modifiers.vb:
  - Public
  - Overridable
- uid: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.DestinationTable
  commentId: P:Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.DestinationTable
  id: DestinationTable
  parent: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy
  langs:
  - csharp
  - vb
  name: DestinationTable
  nameWithType: JobConfigurationTableCopy.DestinationTable
  fullName: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.DestinationTable
  type: Property
  source:
    remote:
      path: Src/Generated/Google.Apis.Bigquery.v2/Google.Apis.Bigquery.v2.cs
      branch: master
      repo: https://github.com/google/google-api-dotnet-client
    id: DestinationTable
    path: Src/Generated/Google.Apis.Bigquery.v2/Google.Apis.Bigquery.v2.cs
    startLine: 3588
  assemblies:
  - Google.Apis.Bigquery.v2
  namespace: Google.Apis.Bigquery.v2.Data
  summary: '[Required] The destination table'
  example: []
  syntax:
    content: public virtual TableReference DestinationTable { get; set; }
    parameters: []
    return:
      type: Google.Apis.Bigquery.v2.Data.TableReference
    content.vb: Public Overridable Property DestinationTable As TableReference
  overload: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.DestinationTable*
  modifiers.csharp:
  - public
  - virtual
  - get
  - set
  modifiers.vb:
  - Public
  - Overridable
- uid: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.SourceTable
  commentId: P:Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.SourceTable
  id: SourceTable
  parent: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy
  langs:
  - csharp
  - vb
  name: SourceTable
  nameWithType: JobConfigurationTableCopy.SourceTable
  fullName: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.SourceTable
  type: Property
  source:
    remote:
      path: Src/Generated/Google.Apis.Bigquery.v2/Google.Apis.Bigquery.v2.cs
      branch: master
      repo: https://github.com/google/google-api-dotnet-client
    id: SourceTable
    path: Src/Generated/Google.Apis.Bigquery.v2/Google.Apis.Bigquery.v2.cs
    startLine: 3592
  assemblies:
  - Google.Apis.Bigquery.v2
  namespace: Google.Apis.Bigquery.v2.Data
  summary: '[Pick one] Source table to copy.'
  example: []
  syntax:
    content: public virtual TableReference SourceTable { get; set; }
    parameters: []
    return:
      type: Google.Apis.Bigquery.v2.Data.TableReference
    content.vb: Public Overridable Property SourceTable As TableReference
  overload: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.SourceTable*
  modifiers.csharp:
  - public
  - virtual
  - get
  - set
  modifiers.vb:
  - Public
  - Overridable
- uid: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.SourceTables
  commentId: P:Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.SourceTables
  id: SourceTables
  parent: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy
  langs:
  - csharp
  - vb
  name: SourceTables
  nameWithType: JobConfigurationTableCopy.SourceTables
  fullName: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.SourceTables
  type: Property
  source:
    remote:
      path: Src/Generated/Google.Apis.Bigquery.v2/Google.Apis.Bigquery.v2.cs
      branch: master
      repo: https://github.com/google/google-api-dotnet-client
    id: SourceTables
    path: Src/Generated/Google.Apis.Bigquery.v2/Google.Apis.Bigquery.v2.cs
    startLine: 3596
  assemblies:
  - Google.Apis.Bigquery.v2
  namespace: Google.Apis.Bigquery.v2.Data
  summary: '[Pick one] Source tables to copy.'
  example: []
  syntax:
    content: public virtual IList<TableReference> SourceTables { get; set; }
    parameters: []
    return:
      type: System.Collections.Generic.IList{Google.Apis.Bigquery.v2.Data.TableReference}
    content.vb: Public Overridable Property SourceTables As IList(Of TableReference)
  overload: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.SourceTables*
  modifiers.csharp:
  - public
  - virtual
  - get
  - set
  modifiers.vb:
  - Public
  - Overridable
- uid: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.WriteDisposition
  commentId: P:Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.WriteDisposition
  id: WriteDisposition
  parent: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy
  langs:
  - csharp
  - vb
  name: WriteDisposition
  nameWithType: JobConfigurationTableCopy.WriteDisposition
  fullName: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.WriteDisposition
  type: Property
  source:
    remote:
      path: Src/Generated/Google.Apis.Bigquery.v2/Google.Apis.Bigquery.v2.cs
      branch: master
      repo: https://github.com/google/google-api-dotnet-client
    id: WriteDisposition
    path: Src/Generated/Google.Apis.Bigquery.v2/Google.Apis.Bigquery.v2.cs
    startLine: 3605
  assemblies:
  - Google.Apis.Bigquery.v2
  namespace: Google.Apis.Bigquery.v2.Data
  summary: >-
    [Optional] Specifies the action that occurs if the destination table already exists. The following

    values are supported: WRITE_TRUNCATE: If the table already exists, BigQuery overwrites the table data.

    WRITE_APPEND: If the table already exists, BigQuery appends the data to the table. WRITE_EMPTY: If the table

    already exists and contains data, a &apos;duplicate&apos; error is returned in the job result. The default value is

    WRITE_EMPTY. Each action is atomic and only occurs if BigQuery is able to complete the job successfully.

    Creation, truncation and append actions occur as one atomic update upon job completion.
  example: []
  syntax:
    content: public virtual string WriteDisposition { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Overridable Property WriteDisposition As String
  overload: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.WriteDisposition*
  modifiers.csharp:
  - public
  - virtual
  - get
  - set
  modifiers.vb:
  - Public
  - Overridable
- uid: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.ETag
  commentId: P:Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.ETag
  id: ETag
  parent: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy
  langs:
  - csharp
  - vb
  name: ETag
  nameWithType: JobConfigurationTableCopy.ETag
  fullName: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.ETag
  type: Property
  source:
    remote:
      path: Src/Generated/Google.Apis.Bigquery.v2/Google.Apis.Bigquery.v2.cs
      branch: master
      repo: https://github.com/google/google-api-dotnet-client
    id: ETag
    path: Src/Generated/Google.Apis.Bigquery.v2/Google.Apis.Bigquery.v2.cs
    startLine: 3609
  assemblies:
  - Google.Apis.Bigquery.v2
  namespace: Google.Apis.Bigquery.v2.Data
  summary: The ETag of the item.
  example: []
  syntax:
    content: public virtual string ETag { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Overridable Property ETag As String
  overload: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.ETag*
  modifiers.csharp:
  - public
  - virtual
  - get
  - set
  modifiers.vb:
  - Public
  - Overridable
references:
- uid: Google.Apis.Bigquery.v2.Data
  commentId: N:Google.Apis.Bigquery.v2.Data
  isExternal: false
  name: Google.Apis.Bigquery.v2.Data
  nameWithType: Google.Apis.Bigquery.v2.Data
  fullName: Google.Apis.Bigquery.v2.Data
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.CreateDisposition*
  commentId: Overload:Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.CreateDisposition
  isExternal: false
  name: CreateDisposition
  nameWithType: JobConfigurationTableCopy.CreateDisposition
  fullName: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.CreateDisposition
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.DestinationEncryptionConfiguration*
  commentId: Overload:Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.DestinationEncryptionConfiguration
  isExternal: false
  name: DestinationEncryptionConfiguration
  nameWithType: JobConfigurationTableCopy.DestinationEncryptionConfiguration
  fullName: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.DestinationEncryptionConfiguration
- uid: Google.Apis.Bigquery.v2.Data.EncryptionConfiguration
  commentId: T:Google.Apis.Bigquery.v2.Data.EncryptionConfiguration
  parent: Google.Apis.Bigquery.v2.Data
  isExternal: false
  name: EncryptionConfiguration
  nameWithType: EncryptionConfiguration
  fullName: Google.Apis.Bigquery.v2.Data.EncryptionConfiguration
- uid: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.DestinationTable*
  commentId: Overload:Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.DestinationTable
  isExternal: false
  name: DestinationTable
  nameWithType: JobConfigurationTableCopy.DestinationTable
  fullName: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.DestinationTable
- uid: Google.Apis.Bigquery.v2.Data.TableReference
  commentId: T:Google.Apis.Bigquery.v2.Data.TableReference
  parent: Google.Apis.Bigquery.v2.Data
  isExternal: false
  name: TableReference
  nameWithType: TableReference
  fullName: Google.Apis.Bigquery.v2.Data.TableReference
- uid: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.SourceTable*
  commentId: Overload:Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.SourceTable
  isExternal: false
  name: SourceTable
  nameWithType: JobConfigurationTableCopy.SourceTable
  fullName: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.SourceTable
- uid: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.SourceTables*
  commentId: Overload:Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.SourceTables
  isExternal: false
  name: SourceTables
  nameWithType: JobConfigurationTableCopy.SourceTables
  fullName: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.SourceTables
- uid: System.Collections.Generic.IList{Google.Apis.Bigquery.v2.Data.TableReference}
  commentId: T:System.Collections.Generic.IList{Google.Apis.Bigquery.v2.Data.TableReference}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IList`1
  name: IList<TableReference>
  nameWithType: IList<TableReference>
  fullName: System.Collections.Generic.IList<Google.Apis.Bigquery.v2.Data.TableReference>
  nameWithType.vb: IList(Of TableReference)
  fullName.vb: System.Collections.Generic.IList(Of Google.Apis.Bigquery.v2.Data.TableReference)
  name.vb: IList(Of TableReference)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    nameWithType: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: Google.Apis.Bigquery.v2.Data.TableReference
    name: TableReference
    nameWithType: TableReference
    fullName: Google.Apis.Bigquery.v2.Data.TableReference
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    nameWithType: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Google.Apis.Bigquery.v2.Data.TableReference
    name: TableReference
    nameWithType: TableReference
    fullName: Google.Apis.Bigquery.v2.Data.TableReference
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.IList`1
  commentId: T:System.Collections.Generic.IList`1
  isExternal: true
  name: IList<T>
  nameWithType: IList<T>
  fullName: System.Collections.Generic.IList<T>
  nameWithType.vb: IList(Of T)
  fullName.vb: System.Collections.Generic.IList(Of T)
  name.vb: IList(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    nameWithType: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    nameWithType: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: false
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
- uid: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.WriteDisposition*
  commentId: Overload:Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.WriteDisposition
  isExternal: false
  name: WriteDisposition
  nameWithType: JobConfigurationTableCopy.WriteDisposition
  fullName: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.WriteDisposition
- uid: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.ETag*
  commentId: Overload:Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.ETag
  isExternal: false
  name: ETag
  nameWithType: JobConfigurationTableCopy.ETag
  fullName: Google.Apis.Bigquery.v2.Data.JobConfigurationTableCopy.ETag
