### YamlMime:ManagedReference
items:
- uid: Grpc.Core.ChannelCredentialsConfiguratorBase
  commentId: T:Grpc.Core.ChannelCredentialsConfiguratorBase
  id: ChannelCredentialsConfiguratorBase
  parent: Grpc.Core
  children:
  - Grpc.Core.ChannelCredentialsConfiguratorBase.SetCompositeCredentials(System.Object,Grpc.Core.ChannelCredentials,Grpc.Core.CallCredentials)
  - Grpc.Core.ChannelCredentialsConfiguratorBase.SetInsecureCredentials(System.Object)
  - Grpc.Core.ChannelCredentialsConfiguratorBase.SetSslCredentials(System.Object,System.String,Grpc.Core.KeyCertificatePair,Grpc.Core.VerifyPeerCallback)
  langs:
  - csharp
  - vb
  name: ChannelCredentialsConfiguratorBase
  nameWithType: ChannelCredentialsConfiguratorBase
  fullName: Grpc.Core.ChannelCredentialsConfiguratorBase
  type: Class
  source:
    remote:
      path: src/csharp/Grpc.Core.Api/ChannelCredentialsConfiguratorBase.cs
      branch: v1.27.x
      repo: https://github.com/grpc/grpc
    id: ChannelCredentialsConfiguratorBase
    path: src/csharp/Grpc.Core.Api/ChannelCredentialsConfiguratorBase.cs
    startLine: 26
  assemblies:
  - Grpc.Core.Api
  namespace: Grpc.Core
  summary: "\nBase class for objects that can consume configuration from <code>CallCredentials</code> objects.\nNote: experimental API that can change or be removed without any prior notice.\n"
  example: []
  syntax:
    content: public abstract class ChannelCredentialsConfiguratorBase
    content.vb: Public MustInherit Class ChannelCredentialsConfiguratorBase
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - abstract
  - class
  modifiers.vb:
  - Public
  - MustInherit
  - Class
- uid: Grpc.Core.ChannelCredentialsConfiguratorBase.SetInsecureCredentials(System.Object)
  commentId: M:Grpc.Core.ChannelCredentialsConfiguratorBase.SetInsecureCredentials(System.Object)
  id: SetInsecureCredentials(System.Object)
  parent: Grpc.Core.ChannelCredentialsConfiguratorBase
  langs:
  - csharp
  - vb
  name: SetInsecureCredentials(Object)
  nameWithType: ChannelCredentialsConfiguratorBase.SetInsecureCredentials(Object)
  fullName: Grpc.Core.ChannelCredentialsConfiguratorBase.SetInsecureCredentials(System.Object)
  type: Method
  source:
    remote:
      path: src/csharp/Grpc.Core.Api/ChannelCredentialsConfiguratorBase.cs
      branch: v1.27.x
      repo: https://github.com/grpc/grpc
    id: SetInsecureCredentials
    path: src/csharp/Grpc.Core.Api/ChannelCredentialsConfiguratorBase.cs
    startLine: 31
  assemblies:
  - Grpc.Core.Api
  namespace: Grpc.Core
  summary: "\nConfigures the credentials to use insecure credentials.\n"
  example: []
  syntax:
    content: public abstract void SetInsecureCredentials(object state)
    parameters:
    - id: state
      type: System.Object
    content.vb: Public MustOverride Sub SetInsecureCredentials(state As Object)
  overload: Grpc.Core.ChannelCredentialsConfiguratorBase.SetInsecureCredentials*
  modifiers.csharp:
  - public
  - abstract
  modifiers.vb:
  - Public
  - MustOverride
- uid: Grpc.Core.ChannelCredentialsConfiguratorBase.SetSslCredentials(System.Object,System.String,Grpc.Core.KeyCertificatePair,Grpc.Core.VerifyPeerCallback)
  commentId: M:Grpc.Core.ChannelCredentialsConfiguratorBase.SetSslCredentials(System.Object,System.String,Grpc.Core.KeyCertificatePair,Grpc.Core.VerifyPeerCallback)
  id: SetSslCredentials(System.Object,System.String,Grpc.Core.KeyCertificatePair,Grpc.Core.VerifyPeerCallback)
  parent: Grpc.Core.ChannelCredentialsConfiguratorBase
  langs:
  - csharp
  - vb
  name: SetSslCredentials(Object, String, KeyCertificatePair, VerifyPeerCallback)
  nameWithType: ChannelCredentialsConfiguratorBase.SetSslCredentials(Object, String, KeyCertificatePair, VerifyPeerCallback)
  fullName: Grpc.Core.ChannelCredentialsConfiguratorBase.SetSslCredentials(System.Object, System.String, Grpc.Core.KeyCertificatePair, Grpc.Core.VerifyPeerCallback)
  type: Method
  source:
    remote:
      path: src/csharp/Grpc.Core.Api/ChannelCredentialsConfiguratorBase.cs
      branch: v1.27.x
      repo: https://github.com/grpc/grpc
    id: SetSslCredentials
    path: src/csharp/Grpc.Core.Api/ChannelCredentialsConfiguratorBase.cs
    startLine: 36
  assemblies:
  - Grpc.Core.Api
  namespace: Grpc.Core
  summary: "\nConfigures the credentials to use <code>SslCredentials</code>.\n"
  example: []
  syntax:
    content: public abstract void SetSslCredentials(object state, string rootCertificates, KeyCertificatePair keyCertificatePair, VerifyPeerCallback verifyPeerCallback)
    parameters:
    - id: state
      type: System.Object
    - id: rootCertificates
      type: System.String
    - id: keyCertificatePair
      type: Grpc.Core.KeyCertificatePair
    - id: verifyPeerCallback
      type: Grpc.Core.VerifyPeerCallback
    content.vb: Public MustOverride Sub SetSslCredentials(state As Object, rootCertificates As String, keyCertificatePair As KeyCertificatePair, verifyPeerCallback As VerifyPeerCallback)
  overload: Grpc.Core.ChannelCredentialsConfiguratorBase.SetSslCredentials*
  modifiers.csharp:
  - public
  - abstract
  modifiers.vb:
  - Public
  - MustOverride
- uid: Grpc.Core.ChannelCredentialsConfiguratorBase.SetCompositeCredentials(System.Object,Grpc.Core.ChannelCredentials,Grpc.Core.CallCredentials)
  commentId: M:Grpc.Core.ChannelCredentialsConfiguratorBase.SetCompositeCredentials(System.Object,Grpc.Core.ChannelCredentials,Grpc.Core.CallCredentials)
  id: SetCompositeCredentials(System.Object,Grpc.Core.ChannelCredentials,Grpc.Core.CallCredentials)
  parent: Grpc.Core.ChannelCredentialsConfiguratorBase
  langs:
  - csharp
  - vb
  name: SetCompositeCredentials(Object, ChannelCredentials, CallCredentials)
  nameWithType: ChannelCredentialsConfiguratorBase.SetCompositeCredentials(Object, ChannelCredentials, CallCredentials)
  fullName: Grpc.Core.ChannelCredentialsConfiguratorBase.SetCompositeCredentials(System.Object, Grpc.Core.ChannelCredentials, Grpc.Core.CallCredentials)
  type: Method
  source:
    remote:
      path: src/csharp/Grpc.Core.Api/ChannelCredentialsConfiguratorBase.cs
      branch: v1.27.x
      repo: https://github.com/grpc/grpc
    id: SetCompositeCredentials
    path: src/csharp/Grpc.Core.Api/ChannelCredentialsConfiguratorBase.cs
    startLine: 41
  assemblies:
  - Grpc.Core.Api
  namespace: Grpc.Core
  summary: "\nConfigures the credentials to use composite channel credentials (a composite of channel credentials and call credentials).\n"
  example: []
  syntax:
    content: public abstract void SetCompositeCredentials(object state, ChannelCredentials channelCredentials, CallCredentials callCredentials)
    parameters:
    - id: state
      type: System.Object
    - id: channelCredentials
      type: Grpc.Core.ChannelCredentials
    - id: callCredentials
      type: Grpc.Core.CallCredentials
    content.vb: Public MustOverride Sub SetCompositeCredentials(state As Object, channelCredentials As ChannelCredentials, callCredentials As CallCredentials)
  overload: Grpc.Core.ChannelCredentialsConfiguratorBase.SetCompositeCredentials*
  modifiers.csharp:
  - public
  - abstract
  modifiers.vb:
  - Public
  - MustOverride
references:
- uid: Grpc.Core
  commentId: N:Grpc.Core
  name: Grpc.Core
  nameWithType: Grpc.Core
  fullName: Grpc.Core
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Grpc.Core.ChannelCredentialsConfiguratorBase.SetInsecureCredentials*
  commentId: Overload:Grpc.Core.ChannelCredentialsConfiguratorBase.SetInsecureCredentials
  name: SetInsecureCredentials
  nameWithType: ChannelCredentialsConfiguratorBase.SetInsecureCredentials
  fullName: Grpc.Core.ChannelCredentialsConfiguratorBase.SetInsecureCredentials
- uid: Grpc.Core.ChannelCredentialsConfiguratorBase.SetSslCredentials*
  commentId: Overload:Grpc.Core.ChannelCredentialsConfiguratorBase.SetSslCredentials
  name: SetSslCredentials
  nameWithType: ChannelCredentialsConfiguratorBase.SetSslCredentials
  fullName: Grpc.Core.ChannelCredentialsConfiguratorBase.SetSslCredentials
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Grpc.Core.KeyCertificatePair
  commentId: T:Grpc.Core.KeyCertificatePair
  parent: Grpc.Core
  name: KeyCertificatePair
  nameWithType: KeyCertificatePair
  fullName: Grpc.Core.KeyCertificatePair
- uid: Grpc.Core.VerifyPeerCallback
  commentId: T:Grpc.Core.VerifyPeerCallback
  parent: Grpc.Core
  name: VerifyPeerCallback
  nameWithType: VerifyPeerCallback
  fullName: Grpc.Core.VerifyPeerCallback
- uid: Grpc.Core.ChannelCredentialsConfiguratorBase.SetCompositeCredentials*
  commentId: Overload:Grpc.Core.ChannelCredentialsConfiguratorBase.SetCompositeCredentials
  name: SetCompositeCredentials
  nameWithType: ChannelCredentialsConfiguratorBase.SetCompositeCredentials
  fullName: Grpc.Core.ChannelCredentialsConfiguratorBase.SetCompositeCredentials
- uid: Grpc.Core.ChannelCredentials
  commentId: T:Grpc.Core.ChannelCredentials
  parent: Grpc.Core
  name: ChannelCredentials
  nameWithType: ChannelCredentials
  fullName: Grpc.Core.ChannelCredentials
- uid: Grpc.Core.CallCredentials
  commentId: T:Grpc.Core.CallCredentials
  parent: Grpc.Core
  name: CallCredentials
  nameWithType: CallCredentials
  fullName: Grpc.Core.CallCredentials
